BEGIN
    -- Insert suppliers (10)
    FOR i IN 1..10 LOOP
        INSERT INTO suppliers (supplier_id, supplier_name, contact_info)
        VALUES (seq_suppliers.NEXTVAL, 'Supplier ' || i, 'contact' || i || '@example.com / +25078' || LPAD(i,6,'0'));
    END LOOP;

    -- Insert employees (5)
    INSERT INTO employees (employee_id, username, full_name, role_name)
    VALUES (seq_employees.NEXTVAL, 'emp_alex', 'Alex Johnson', 'Sales');
    INSERT INTO employees (employee_id, username, full_name, role_name)
    VALUES (seq_employees.NEXTVAL, 'emp_maya', 'Maya Singh', 'Inventory');
    INSERT INTO employees (employee_id, username, full_name, role_name)
    VALUES (seq_employees.NEXTVAL, 'emp_thabo', 'Thabo N', 'Sales');
    INSERT INTO employees (employee_id, username, full_name, role_name)
    VALUES (seq_employees.NEXTVAL, 'emp_ariella', 'Ariella Ampoze', 'Developer');
    INSERT INTO employees (employee_id, username, full_name, role_name)
    VALUES (seq_employees.NEXTVAL, 'emp_sam', 'Sam Lee', 'Procurement');

    -- Insert holidays (example: upcoming month sample)
    INSERT INTO holidays (holiday_date, description) VALUES (TRUNC(SYSDATE)+4, 'Local Holiday A');
    INSERT INTO holidays (holiday_date, description) VALUES (TRUNC(SYSDATE)+10, 'Local Holiday B');

    COMMIT;
END;
/
-- Insert many products (300)
DECLARE
    v_supplier_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_supplier_count FROM suppliers;
    FOR i IN 1..300 LOOP
        INSERT INTO products (product_id, product_name, category, unit_price, stock_quantity, reorder_level, supplier_id)
        VALUES (
            seq_products.NEXTVAL,
            'Product ' || LPAD(i,3,'0'),
            CASE WHEN MOD(i,4)=0 THEN 'Grocery' WHEN MOD(i,4)=1 THEN 'Household' WHEN MOD(i,4)=2 THEN 'Electronics' ELSE 'PersonalCare' END,
            ROUND(DBMS_RANDOM.VALUE(100,50000),2),
            TRUNC(DBMS_RANDOM.VALUE(5,200)),  -- stock
            TRUNC(DBMS_RANDOM.VALUE(5,30)),   -- reorder_level
            1 + MOD(i, v_supplier_count)
        );
    END LOOP;
    COMMIT;
END;
/

-- Insert sales (500) with randomized product choices and dates in last 120 days
BEGIN
    FOR i IN 1..500 LOOP
        INSERT INTO sales(sale_id, product_id, quantity_sold, sale_date, created_by)
        VALUES (
            seq_sales.NEXTVAL,
            1 + TRUNC(DBMS_RANDOM.VALUE(0,300)), -- random product_id 1..300
            1 + TRUNC(DBMS_RANDOM.VALUE(1,10)),   -- quantity 1..10
            SYSDATE - TRUNC(DBMS_RANDOM.VALUE(0,120)), -- in last 120 days
            CASE WHEN DBMS_RANDOM.VALUE(0,1) < 0.5 THEN 'emp_alex' ELSE 'emp_maya' END
        );

        -- Update product stock quantity accordingly (simple approach; ignore negative check)
        UPDATE products
        SET stock_quantity = GREATEST(0, stock_quantity - (1 + TRUNC(DBMS_RANDOM.VALUE(1,10))))
        WHERE product_id = 1 + TRUNC(DBMS_RANDOM.VALUE(0,300));
    END LOOP;
    COMMIT;
END;
/

-- Create a few inventory_log entries (reflecting sales)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM sales;
    FOR r IN (SELECT sale_id, product_id, quantity_sold, sale_date, created_by FROM sales WHERE ROWNUM <= 200) LOOP
        INSERT INTO inventory_log (log_id, product_id, action_type, quantity_changed, log_date, created_by)
        VALUES (seq_inventory_log.NEXTVAL, r.product_id, 'SALE', -r.quantity_sold, r.sale_date, r.created_by);
    END LOOP;
    COMMIT;
END;
/

-- Leave reorder_requests empty initially — they will be auto-generated by triggers/procedures.
