CREATE TABLE suppliers (
    supplier_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name    VARCHAR2(100) NOT NULL,
    contact_info     VARCHAR2(200)
);


CREATE TABLE employees (
    employee_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR2(50) UNIQUE NOT NULL,
    full_name        VARCHAR2(120),
    role_name        VARCHAR2(50)
);


CREATE TABLE products (
    product_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name     VARCHAR2(150) NOT NULL,
    category         VARCHAR2(50),
    unit_price       NUMBER(12,2),
    stock_quantity   NUMBER DEFAULT 0 NOT NULL,
    reorder_level    NUMBER DEFAULT 0 NOT NULL,
    supplier_id      NUMBER,
    CONSTRAINT fk_prod_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);


CREATE TABLE sales (
    sale_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       NUMBER NOT NULL,
    quantity_sold    NUMBER NOT NULL,
    sale_date        DATE DEFAULT SYSDATE NOT NULL,
    created_by       VARCHAR2(50),
    CONSTRAINT fk_sales_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);


CREATE TABLE inventory_log (
    log_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       NUMBER NOT NULL,
    action_type      VARCHAR2(20) NOT NULL, 
    quantity_changed NUMBER NOT NULL,
    log_date         DATE DEFAULT SYSDATE NOT NULL,
    created_by       VARCHAR2(50),
    CONSTRAINT fk_log_prod FOREIGN KEY (product_id) REFERENCES products(product_id)
);


CREATE TABLE reorder_requests (
    request_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       NUMBER NOT NULL,
    reorder_quantity NUMBER NOT NULL,
    request_date     DATE DEFAULT SYSDATE NOT NULL,
    status           VARCHAR2(20) DEFAULT 'PENDING',
    created_by       VARCHAR2(50),   
    CONSTRAINT fk_rr_prod FOREIGN KEY (product_id) REFERENCES products(product_id)
);


CREATE TABLE holidays (
    holiday_date     DATE PRIMARY KEY,
    description      VARCHAR2(200)
);


CREATE TABLE audit_log (
    log_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_name      VARCHAR2(128),
    action_type      VARCHAR2(10),
    action_date      DATE DEFAULT SYSDATE,
    username         VARCHAR2(50),
    status           VARCHAR2(20), 
    message          VARCHAR2(4000)
);
